### ISSUE TITLE
How do I add more sources

### ISSUE THREAD

**Issue by Rawkush** [Michael24884/TaiYaKiAnime#16]
I wanna contribute to the project but How do I make sources for the app to use, I have scraped some anime websites how do I convert them into the sources for this app. Some guidance will be appreciated 😊

**Comment by ArjixGamer** [comment]
Honestly, just from looking at the files I too have a problem finding where the providers are at.

**Comment by ArjixGamer** [comment]
I asked in the discord server and the answer is here:
https://github.com/Michael24884/taiyaki-repos/blob/master/src/sources_list.json

but it is planned that they are moved to this repo so i would suggest waiting for that
