### ISSUE TITLE
The website doesn't exist when trying to download for Android

### ISSUE THREAD

**Issue by CookieSalsa** [Michael24884/TaiYaKiAnime#17]
I'm trying to download it for Android but it takes me to Error 404 for the website. Thank you!

**Comment by ArjixGamer** [comment]
Because you clearly didn't even click the correct link....
That link was for a github hosted website for taiyaki, not the downloads page....
If you want to download it go to https://github.com/Michael24884/TaiYaKiAnime/releases

**Comment by ArjixGamer** [comment]
PS: It looks like the latest pre-release is not working, so install an older version.

**Comment by ArjixGamer** [comment]
Sorry my bad, it actually was a mistake in the url itself, somehow a comma was at the end of the url when it was not supposed to be there....it's fixed now so you can close this issue
