### ISSUE TITLE
Support AniList.co

### ISSUE THREAD

**Issue by BlackNetCze** [Michael24884/TaiYaKiAnime#2]
Could you please add support for anilist.co?

**Comment by Michael24884** [comment]
Hi there, 
This might actually be the priority as MAL once again blocked their API

**Comment by nate-moo** [comment]
Is there any progress on this?

**Comment by Michael24884** [comment]
> Is there any progress on this?

Taiyaki now has Anilist and MAL support

**Comment by nate-moo** [comment]
Cool, thanks!
