### ISSUE TITLE
Element Blocking Fullscreen

### ISSUE THREAD

**Issue by Masonjar13** [Michael24884/TaiYaKiAnime#25]
There's an element on the screen that overlaps and blocks the fullscreen and other (overscan?) buttons during playback. You can tap them only in the bottom 10% of the  button elements. https://imgur.com/a/xwwqUZO

If no one else is experiencing this issue, I can only assume it's due to my screen resolution (1440x3120).

**Comment by Michael24884** [comment]
Should be fixed in the last ear update

**Comment by Masonjar13** [comment]
Tested release 92, the element is still blocking the top portion of the video player. Once it is in fullscreen, there's no issue, but while it's still vertical, I can't tap on the upper 90% still. I took another screenshot on the new release: https://imgur.com/a/WanRbEm

**Comment by Michael24884** [comment]
Thanks a lot for the info I released a quick fix to this in 92.1.

**Comment by Masonjar13** [comment]
Tested and working, I really appreciate how responsive you were. Thank you for the quick update.
