### ISSUE TITLE
Cannot scroll down update page on start

### ISSUE THREAD

**Issue by AlexMiniReal** [Michael24884/TaiYaKiAnime#34]
I can't use the app because the app makes it impossible for me to scroll down the update page.
Phone: Xiaomi Mi A2 Lite
Version: 92.1.
Universal Release.apk

**Comment by Michael24884** [comment]
On android just press the back button

**Comment by AlexMiniReal** [comment]
Ok, solved. I have another request. Could you please add animeworld.tv as a source? It's the best site to watch anime in Italy.

**Comment by ArjixGamer** [comment]
Please use an issue for a single purpose.
If you want to request a source either make a new issue or join our discord server and send it in #request-a-source or #bilangual-source-request

**Comment by AlexMiniReal** [comment]
Ok thanks for everything, could you please send me the discord link so i can ask the source?

**Comment by ArjixGamer** [comment]
It's in the app...
Just go to the settings and scroll down.
