### ISSUE TITLE
How do i download the app

### ISSUE THREAD

**Issue by mrpoophead** [Michael24884/TaiYaKiAnime#36]
I don't know how to download the app lol plss help

**Comment by ArjixGamer** [comment]
Would be helpful if you also included what type of phone you have...
iOS or Android?

**Comment by LunarMarie** [comment]
Same i dont know where or how to download the app. I have an android

**Comment by ArjixGamer** [comment]
So you know how to make a github issue, but you dont know how to download releases from github?

**Comment by ArjixGamer** [comment]
Go to this link
https://github.com/TaiyakiContainer/TaiYaKiAnime/releases/tag/92.1

**Comment by ArjixGamer** [comment]
If you are on iOS you will need to join the TestFlight...
and its usually full...
so you might not be able to download it on iOS
