### ISSUE TITLE
Testflight download

### ISSUE THREAD

**Issue by Waloodi** [Michael24884/TaiYaKiAnime#4]
So apple has made this really cool app where you can beta test apps and i think it would be a great place to beta test the app, another great anime app nineanimator hosts their app their and some other places too.

**Comment by Michael24884** [comment]
Hey, thanks for the tip. I like the idea and was expecting to release this app on it once I had the manga alt ready as well

**Comment by Waloodi** [comment]
Thats awesome, thanks for this amazing app too
