### ISSUE TITLE
The What's new page (not working)

### ISSUE THREAD

**Issue by typicalrohan** [Michael24884/TaiYaKiAnime#44]
So I just download the app and it opened on the what's new page it's says if I don't want to read through it just pull down, I try that but it doesn't work, I keep restarting the app but I can't get off this page. Pls fix 🙏

**Comment by Michael24884** [comment]
Have you tried pressing the back button?

**Comment by Macha-ai** [comment]
Same as @typicalrohan

**Comment by Macha-ai** [comment]
Plz fix to it
