### ISSUE TITLE
The application cannot be installed on Redmi Note 7

### ISSUE THREAD

**Issue by RutsuKun** [Michael24884/TaiYaKiAnime#5]
I don't know what is the reason
![Screenshot_2020-02-06-13-06-31-396_com android settings](https://user-images.githubusercontent.com/14915249/73935809-b46b6500-48e1-11ea-8c2c-88789fede3c9.jpg)
![Screenshot_2020-02-06-13-06-25-150_com google android packageinstaller](https://user-images.githubusercontent.com/14915249/73935813-b6cdbf00-48e1-11ea-97bd-23dded652c93.jpg)

**Comment by Michael24884** [comment]
Have you tried all 3 architectural apks? You might need to try each one to find the correct arch for your device

**Comment by Michael24884** [comment]
Closing due to lack of response. Reopen if you’re still having problems.
