### ISSUE TITLE
App not installed.

### ISSUE THREAD

**Issue by Aysidia** [Michael24884/TaiYaKiAnime#7]
I tried all 3 of the .APKs in the latest release assets, but all of them lead to the same "App not installed." screen. What went wrong?

**Comment by sovietanthem** [comment]
Pretty sure that either means the apk file is corrupted or its something with your phone do you have another phone lying around? If so try it with that if its the same problem then the apk might be corrupted

**Comment by jeromesumy** [comment]
You can use SAI
I use this to install it in my phone
https://play.google.com/store/apps/details?id=com.aefyr.sai

**Comment by ArjixGamer** [comment]
Do not use SAI for this, this is not an app bundle (split apk).
If you are not sure on what apk to install.
Go for the universal one.
[``app-universal-release.apk``](https://github.com/TaiyakiContainer/TaiYaKiAnime/releases/download/92.1/app-universal-release.apk)
